POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "Soda",
    "quantity": 12
}

### 

POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "Bread",
    "quantity": 8
}
### 

POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "Soy Milk",
    "quantity": 2
}
### 

POST http://localhost:3000/products/60137e9e300b1b3fc0ecd4df
Content-Type: application/json

{
    "stars": 2,
    "review": "Soda was too sugary."
}

### 

POST http://localhost:3000/products/60137e9e300b1b3fc0ecd4df
Content-Type: application/json

{
    "stars": 3,
    "review": "The soda didn't tasted old."
}

### 

GET http://localhost:3000/products

###

GET http://localhost:3000/reviews

###

GET http://localhost:3000/products/60137afda49dd231ac725c9d

###

GET http://localhost:3000/reviews/60137b04a49dd231ac725c9e

###

DELETE http://localhost:3000/products/60137a08a49dd231ac725c98

###

DELETE http://localhost:3000/reviews/60137a25a49dd231ac725c9b




########################################


### 

POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "PRODUTO7777",
    "quantity": 2
}
### 

POST http://localhost:3000/products/60137afda49dd231ac725c9d
Content-Type: application/json

{
    "stars": 2,
    "review": "REVIEW7777"
}

### 

PUT http://localhost:3000/products/60137afda49dd231ac725c9d
Content-Type: application/json

{
    "name": "produtinho"
    
}

####

PUT http://localhost:3000/reviews/60137b04a49dd231ac725c9e
Content-Type: application/json

{
    "stars": 6,
    "review": "Agora foi!!!!"
}